#include "vortex/core/input/input_backend.hpp"
#include "raylib.h"

using namespace Vortex;

namespace Vortex::Core::InputBackend
{
    static int TranslateToRaylibKey(KeyCode key)
    {
        switch (key)
        {
        case KeyCode::UNKNOWN:
            return 0;
        case KeyCode::A:
            return KEY_A;
        case KeyCode::B:
            return KEY_B;
        case KeyCode::C:
            return KEY_C;
        case KeyCode::D:
            return KEY_D;
        case KeyCode::E:
            return KEY_E;
        case KeyCode::F:
            return KEY_F;
        case KeyCode::G:
            return KEY_G;
        case KeyCode::H:
            return KEY_H;
        case KeyCode::I:
            return KEY_I;
        case KeyCode::J:
            return KEY_J;
        case KeyCode::K:
            return KEY_K;
        case KeyCode::L:
            return KEY_L;
        case KeyCode::M:
            return KEY_M;
        case KeyCode::N:
            return KEY_N;
        case KeyCode::O:
            return KEY_O;
        case KeyCode::P:
            return KEY_P;
        case KeyCode::Q:
            return KEY_Q;
        case KeyCode::R:
            return KEY_R;
        case KeyCode::S:
            return KEY_S;
        case KeyCode::T:
            return KEY_T;
        case KeyCode::U:
            return KEY_U;
        case KeyCode::V:
            return KEY_V;
        case KeyCode::W:
            return KEY_W;
        case KeyCode::X:
            return KEY_X;
        case KeyCode::Y:
            return KEY_Y;
        case KeyCode::Z:
            return KEY_Z;
        case KeyCode::NUM_0:
            return KEY_ZERO;
        case KeyCode::NUM_1:
            return KEY_ONE;
        case KeyCode::NUM_2:
            return KEY_TWO;
        case KeyCode::NUM_3:
            return KEY_THREE;
        case KeyCode::NUM_4:
            return KEY_FOUR;
        case KeyCode::NUM_5:
            return KEY_FIVE;
        case KeyCode::NUM_6:
            return KEY_SIX;
        case KeyCode::NUM_7:
            return KEY_SEVEN;
        case KeyCode::NUM_8:
            return KEY_EIGHT;
        case KeyCode::NUM_9:
            return KEY_NINE;
        case KeyCode::F1:
            return KEY_F1;
        case KeyCode::F2:
            return KEY_F2;
        case KeyCode::F3:
            return KEY_F3;
        case KeyCode::F4:
            return KEY_F4;
        case KeyCode::F5:
            return KEY_F5;
        case KeyCode::F6:
            return KEY_F6;
        case KeyCode::F7:
            return KEY_F7;
        case KeyCode::F8:
            return KEY_F8;
        case KeyCode::F9:
            return KEY_F9;
        case KeyCode::F10:
            return KEY_F10;
        case KeyCode::F11:
            return KEY_F11;
        case KeyCode::F12:
            return KEY_F12;
        case KeyCode::SPACE:
            return KEY_SPACE;
        case KeyCode::ESC:
            return KEY_ESCAPE;
        case KeyCode::ENTER:
            return KEY_ENTER;
        case KeyCode::TAB:
            return KEY_TAB;
        case KeyCode::BACKSPACE:
            return KEY_BACKSPACE;
        case KeyCode::INSERT:
            return KEY_INSERT;
        case KeyCode::DELETE_KEY:
            return KEY_DELETE;
        case KeyCode::ARROW_RIGHT:
            return KEY_RIGHT;
        case KeyCode::ARROW_LEFT:
            return KEY_LEFT;
        case KeyCode::ARROW_DOWN:
            return KEY_DOWN;
        case KeyCode::ARROW_UP:
            return KEY_UP;
        case KeyCode::PAGE_UP:
            return KEY_PAGE_UP;
        case KeyCode::PAGE_DOWN:
            return KEY_PAGE_DOWN;
        case KeyCode::HOME:
            return KEY_HOME;
        case KeyCode::END:
            return KEY_END;
        case KeyCode::CAPS_LOCK:
            return KEY_CAPS_LOCK;
        case KeyCode::SCROLL_LOCK:
            return KEY_SCROLL_LOCK;
        case KeyCode::NUM_LOCK:
            return KEY_NUM_LOCK;
        case KeyCode::PRINT_SCREEN:
            return KEY_PRINT_SCREEN;
        case KeyCode::PAUSE_KEY:
            return KEY_PAUSE;
        case KeyCode::LEFT_SHIFT:
            return KEY_LEFT_SHIFT;
        case KeyCode::LEFT_CONTROL:
            return KEY_LEFT_CONTROL;
        case KeyCode::LEFT_ALT:
            return KEY_LEFT_ALT;
        case KeyCode::LEFT_SUPER:
            return KEY_LEFT_SUPER;
        case KeyCode::RIGHT_SHIFT:
            return KEY_RIGHT_SHIFT;
        case KeyCode::RIGHT_CONTROL:
            return KEY_RIGHT_CONTROL;
        case KeyCode::RIGHT_ALT:
            return KEY_RIGHT_ALT;
        case KeyCode::RIGHT_SUPER:
            return KEY_RIGHT_SUPER;
        case KeyCode::NUMPAD_0:
            return KEY_KP_0;
        case KeyCode::NUMPAD_1:
            return KEY_KP_1;
        case KeyCode::NUMPAD_2:
            return KEY_KP_2;
        case KeyCode::NUMPAD_3:
            return KEY_KP_3;
        case KeyCode::NUMPAD_4:
            return KEY_KP_4;
        case KeyCode::NUMPAD_5:
            return KEY_KP_5;
        case KeyCode::NUMPAD_6:
            return KEY_KP_6;
        case KeyCode::NUMPAD_7:
            return KEY_KP_7;
        case KeyCode::NUMPAD_8:
            return KEY_KP_8;
        case KeyCode::NUMPAD_9:
            return KEY_KP_9;
        case KeyCode::NUMPAD_DECIMAL:
            return KEY_KP_DECIMAL;
        case KeyCode::NUMPAD_DIVIDE:
            return KEY_KP_DIVIDE;
        case KeyCode::NUMPAD_MULTIPLY:
            return KEY_KP_MULTIPLY;
        case KeyCode::NUMPAD_SUBTRACT:
            return KEY_KP_SUBTRACT;
        case KeyCode::NUMPAD_ADD:
            return KEY_KP_ADD;
        case KeyCode::NUMPAD_ENTER:
            return KEY_KP_ENTER;
        case KeyCode::NUMPAD_EQUAL:
            return KEY_KP_EQUAL;
        case KeyCode::APOSTROPHE:
            return KEY_APOSTROPHE;
        case KeyCode::COMMA:
            return KEY_COMMA;
        case KeyCode::HYPHEN:
            return KEY_MINUS;
        case KeyCode::PLUS:
            return KEY_EQUAL;
        case KeyCode::PERIOD:
            return KEY_PERIOD;
        case KeyCode::FORWARD_SLASH:
            return KEY_SLASH;
        case KeyCode::SEMICOLON:
            return KEY_SEMICOLON;
        case KeyCode::EQUAL:
            return KEY_EQUAL;
        case KeyCode::LEFT_BRACKET:
            return KEY_LEFT_BRACKET;
        case KeyCode::BACKSLASH:
            return KEY_BACKSLASH;
        case KeyCode::RIGHT_BRACKET:
            return KEY_RIGHT_BRACKET;
        case KeyCode::TILDE:
            return KEY_GRAVE;
        default:
            return 0;
        }
    }

    bool IsHardwareKeyPressed(KeyCode key)
    {
        return IsKeyPressed(TranslateToRaylibKey(key));
    }

    bool IsHardwareKeyDown(KeyCode key)
    {
        return IsKeyDown(TranslateToRaylibKey(key));
    }
}